version: '3.1'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
  backend:
    build: backend/
    ports: 
      - 8080:8080
    depends_on:
      - database
  frontend:
    build: frontend/
    ports:
      - 3000:3000
    depends_on:
      - backend
